apiVersion: v1
kind: Service
metadata:
  name: hashcraft-service
spec:
  type: NodePort
  selector:
    app: hashcraft-pod
    type: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30008