name: Build, Optimize and Publish Docker Image to Github Registry

on:
  push:
    branches: ['main']

jobs:
  build:
    if: ${{ contains(github.event.head_commit.message, 'Build Image') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3
      
      - name: Install Slimtoolkit
        shell: bash
        run: |
          curl -L -o ds.tar.gz https://downloads.dockerslim.com/releases/1.40.1/dist_linux.tar.gz
          tar -xvf ds.tar.gz
          mv dist_linux/docker-slim /usr/local/bin/
          mv dist_linux/slim-sensor /usr/local/bin/
          mv dist_linux/slim /usr/local/bin/
      
      - name : update slim
        shell: bash
        run: slim update

      - name: Log in to Github Image Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Optimize Docker Image
        run: slim build --target ghcr.io/startrooper08/hashcraft:main --http-probe=true --expose 80

      - name: Push Optimized Docker Image to Github Registry
        run: docker push ghcr.io/startrooper08/hashcraft.slim
        