name: Release project
on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release
        uses: huggingface/semver-release-action@latest
        with:
           TOKEN: ${{ secrets.GITHUB_TOKEN }}