name: Release project
on:
   push: ["main"]

permissions:
   contents: read

jobs:
   release:
     permissions:
        contents: write # to be able to publish a GitHub release

     name: Release
     runs-on: ubuntu-latest

     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Release
         uses: huggingface/semver-release-action@latest
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}